# The list of all sites which get rendered with the basic template + intern navbar

prefix = "intern"

[[sites]]
name = "betreuer"
file_name = "Betreuer.md"
title = "Für Betreuer"
description = "Für Betreuer des Zeltlagers"

[[sites]]
name = "betreuer-anmeldung"
file_name = "AnmeldungBetreuer.txt"
title = "Betreueranmeldung"
description = "Anmeldung für Betreuer des Zeltlagers"

[[sites]]
name = "betreuer-anmeldung-erfolgreich"
file_name = "AnmeldungBetreuerErfolgreich.md"
title = "Betreueranmeldung erfolgreich"
description = "Betreueranmeldung für’s Zeltlager war erfolgreich"
navbar_visible = false
