# The list of all sites which are shown on the intern navbar

prefix = "intern"

[[sites]]
name = ""
title = "Für Betreuer"

[[sites]]
name = "betreuer-anmeldung"
title = "Betreueranmeldung"

[[sites]]
name = "zuschuesse"
title = "Zuschüsse"
