# The list of all sites visible on the default homepage

prefix = ""

[[sites]]
name = "admin/teilnehmer"
title = "Teilnehmer"
role = "Admin"

[[sites]]
name = "admin/betreuer"
title = "Betreuer"
role = "Admin"

[[sites]]
name = "erwischt/"
title = "Erwischt"
role = "Erwischt"

[[sites]]
name = "anmeldung"
title = "Anmeldung"

[[sites]]
name = "packliste"
title = "Packliste"

[[sites]]
name = "ausstattung"
title = "Ausstattung und Team"

[[sites]]
name = "betreuer"
title = "Für Betreuer"

[[sites]]
name = "datenschutz"
title = "Datenschutz"

[[sites]]
name = "impressum"
title = "Impressum"
