# The list of all sites which get rendered with the basic template

prefix = ""

[[sites]]
name = "startseite"
file_name = "Home.md"
title = "Startseite"
description = "Startseite der Zeltlagerwebseite"

[[sites]]
name = "anmeldung"
file_name = "Anmeldung.txt"
title = "Anmeldung"
description = "Anmeldung für’s Zeltlager"

[[sites]]
name = "anmeldung-erfolgreich"
file_name = "AnmeldungErfolgreich.md"
title = "Anmeldung erfolgreich"
description = "Anmeldung für’s Zeltlager war erfolgreich"
navbar_visible = false

[[sites]]
name = "programm"
file_name = "Programm.md"
title = "Programm"
description = "Programm des Zeltlagers"

[[sites]]
name = "team"
file_name = "Team.md"
title = "Team"
description = "Team des Zeltlagers"

[[sites]]
name = "ausstattung"
file_name = "Ausstattung.md"
title = "Ausstattung"
description = "Ausstattung des Zeltlagers"

[[sites]]
name = "agb"
file_name = "Agb.html"
title = "Allgemeine Geschäftsbedingungen"
description = "Allgemeine Geschäftsbedingungen des Zeltlagers"
navbar_visible = false

[[sites]]
name = "datenschutz"
file_name = "Datenschutz.html"
title = "Datenschutz"
description = "Datenschutzerklärung der Zeltlagerwebsite"
navbar_visible = false

[[sites]]
name = "impressum"
file_name = "Impressum.html"
title = "Impressum"
description = "Impressum der Zeltlagerwebsite"

[[sites]]
name = "404"
file_name = "404.md"
title = "404 - Not Found"
description = "404 - Not Found"
navbar_visible = false
