[package]
name = "zeltlager-website"
version = "0.1.0"
authors = ["Flakebi <flakebi@t-online.de>"]
edition = "2018"

[dependencies]
actix = "0.9"
actix-files = "0.2"
actix-http = "1"
actix-identity = "0.2"
actix-rt = "1"
actix-web = "2"
anyhow = "1"
base64 = "0.13"
chrono = { version = "0.4", features = ["serde"] }
csv = "1"
diesel = { version = "1.4", features = ["chrono", "postgres", "network-address"] }
diesel_migrations = "1.4"
dotenv = "0.15"
env_logger = "0.9"
futures = "0.3"
ipnetwork = "0.18"
lettre = "0.9"
lettre_email = "0.9"
log = "0.4"
mime = "0.3"
native-tls = "0.2"
notify = "4"
pulldown-cmark = { version = "0.8", default-features = false }
printpdf = "0.4"
rand = "0.8"
rpassword = "5"
scrypt = "0.7"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
structopt = { version = "0.3", default-features = false }
strum = "0.21"
strum_macros = "0.21"
t4rust-derive = "0.3"
toml = "0.5"
tokio = { version = "0.2", features = ["macros"] }
url = "2"

# Compile in release mode to speed up password checking
[profile.dev.package.scrypt]
opt-level = 3
