[package]
name = "zeltlager-website"
version = "0.1.0"
authors = ["Flakebi <flakebi@t-online.de>"]

[dependencies]
actix = "0.5"
actix-web = "0.4"
bytes = "0.4"
chrono = "0.4"
diesel = { version = "1", features = ["chrono", "large-tables", "postgres"] }
dotenv = "0.9"
env_logger = "0.5"
failure = "0.1"
futures = "0.1"
lettre = "0.7"
lettre_email = "0.7"
log = "0.4"
mime = "0.3"
pulldown-cmark = { version = "0.0", default-features = false }
serde = "1"
serde_derive = "1"
t4rust-derive = { git = "https://github.com/ReSpeak/t4rust.git" }
toml = "0.4"
