[package]
name = "zeltlager-website"
version = "0.1.0"
authors = ["Flakebi <flakebi@t-online.de>"]

[dependencies]
actix = "0.7"
actix-web = "0.7"
bytes = "0.4"
chrono = "0.4"
csv = "1"
diesel = { version = "1.2", features = ["chrono", "postgres", "network-address"] }
dotenv = "0.13"
env_logger = "0.6"
failure = "0.1"
futures = "0.1"
ipnetwork = "0.13"
lettre = "0.9"
lettre_email = "0.9"
scrypt = "0.2"
log = "0.4"
mime = "0.3"
native-tls = "0.2"
notify = "4"
pulldown-cmark = { version = "0.2", default-features = false }
rand = "0.6"
reqwest = "0.9"
rpassword = "2"
sentry = "0.15"
serde = "1"
serde_derive = "1"
structopt = "0.2"
strum = "0.13"
strum_macros = "0.13"
t4rust-derive = { git = "https://github.com/ReSpeak/t4rust.git" }
toml = "0.4"
url = "1"

[patch.crates-io]
lettre = { git = "https://github.com/lettre/lettre", rev = "c988b17" }
lettre_email = { git = "https://github.com/lettre/lettre", rev = "c988b17" }
