# The list of all sites which get rendered with the basic template

[[sites]]
name = "Home.html"
title = "Startseite"
description = "Startseite des Zeltlagers"

[[sites]]
name = "Anmeldung.html"
title = "Anmeldung"
description = "Anmeldung für’s Zeltlager"

[[sites]]
name = "Programm.html"
title = "Programm"
description = "Programm des Zeltlagers"

[[sites]]
name = "Team.html"
title = "Team"
description = "Team des Zeltlagers"

[[sites]]
name = "Ausstattung.html"
title = "Ausstattung"
description = "Ausstattung des Zeltlagers"
